### ISSUE TITLE
Having trouble reproducing example -- nlpopt_interval_bnb

### ISSUE THREAD

**Issue by ca0h** [PSORLab/EAGO-notebooks#2]
I ran into two issues when reproducing [nlpopt_interval_bnb example](https://github.com/PSORLab/EAGO-notebooks/blob/master/notebooks/nlpopt_interval_bnb.ipynb)

1. In "lower_problem!", x is defined twice (an EAGO.Optimizer and an array of intervals). I changed the latter one as 

```
xvalue = Interval.(lower, upper)
F = sin(xvalue[1])*xvalue[2]^2-cos(xvalue[3])/xvalue[4]
```

2. After resolving the previous issue, I got

```
ERROR: LoadError: UndefVarError: intv_lo not defined
Stacktrace:
 [1] cut_condition(::IntervalExt, ::Optimizer{GLPK.Optimizer,Ipopt.Optimizer}) at ......\.julia\packages\EAGO\Fr4Op\src\eago_optimizer\subroutines.jl:718
```

Versions:
- Julia: 1.1
- EAGO: v0.3.0

**Comment by mewilhel** [comment]
Apologies again. Since we aren't defining functions using JuMP we need to introduce a new cut_condition to get around this problem in the same manner we do for the lower and upper problem. I've updated the workbook to include this.

**Comment by ca0h** [comment]
Thanks for the response. : )
